version: '3.9'
services:
  webserver:
    container_name: sakura-api
    image: node:alpine
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: sh -c "cd /app && npm run server-prd"
    networks:
      - server-mysql

  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testuser1234
      MYSQL_DATABASE: sakura_db
      MYSQL_USER: testexample
      MYSQL_PASSWORD: testexample
    networks:
      - server-mysql

networks:
  server-mysql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24