version: '3'
services:
  server-container:
    container_name: sakura-api
    image: alpine
    restart: always
    ports:
      - 8080:8080
    networks:
      - server-mysql

  mysql-container:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testuser  
    networks:
      - server-mysql

networks:
  server-mysql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24